cash_machine/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^atm/', include('webinterface.urls', namespace='webinterface')),
]

webinterface/urls.py
from django.conf.urls import url

from webinterface.views import *


urlpatterns = [
    url(r'^$', AtmView.as_view(), name='atm'),
    url(r'^pin/$', PinView.as_view(), name='pin'),
    url(r'^operations/$', OperationsView.as_view(), name='operations'),
    url(r'^error/(?P<error>\w+)', ErrorView.as_view(), name='error'),
    url(r'^quit/$', ExitView.as_view(), name='exit'),
    url(r'^balance/$', BalanceView.as_view(), name='balance'),
    url(r'^withdraw/$', WithdrawView.as_view(), name='withdraw'),
]

webinterface/models.py
from django.db import models
from django_extensions.db.fields.encrypted import EncryptedCharField
from django.contrib.auth.hashers import make_password
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class Card(models.Model):
    number = EncryptedCharField(verbose_name=_('Card bumber'),
                             max_length=128)
    hashed = models.CharField(verbose_name=_('Hashed'),
                              max_length=128)
    pin = models.CharField(verbose_name=_('Card pincode'),
                             max_length=128)
    pin_attempts = models.SmallIntegerField(verbose_name=_('PIN attempts'),
                                            default=0)
    pin_block = models.BooleanField(verbose_name=_('PIN block'),
                                    default=False)
    balance = models.DecimalField(verbose_name=_('Card balance'),
                                  max_digits=19,
                                  decimal_places=2)
    last_modified = models.DateTimeField(verbose_name=_('Last modified'),
                                         auto_now=True)

    def save(self, *args, **kwargs):
        self.hashed = make_password(self.number, salt=settings.SECRET_KEY)
        self.pin = make_password(self.pin, salt=settings.SECRET_KEY)
        super(Card, self).save(*args, **kwargs)

    def  __unicode__(self):
        return str(self.id)

    class Meta:
        verbose_name = _('Card')
        verbose_name_plural = _('Cards')


class Operations(models.Model):
    # card = models.ForeignKey('Card', verbose_name=_('Card'))
    card = EncryptedCharField(verbose_name=_('Card bumber'),
                              max_length=128)
    timestamp = models.DateTimeField(verbose_name=_('Timestamp'),
                                 auto_now_add=True)
    code =  models.CharField(verbose_name=_('Operation code'),
                             max_length=32)
    sum = models.DecimalField(verbose_name=_('Operation ammount'),
                               max_digits=19,
                               decimal_places=2,
                               null=True,
                               blank=True)

    def  __unicode__(self):
        return str(self.id)

    class Meta:
        verbose_name = _('Operation')
        verbose_name_plural = _('Operations')

webinterface/forms.py
from django import forms


class CardNumForm(forms.Form):
    number = forms.CharField()


class CardPinForm(forms.Form):
    pin = forms.CharField(widget=forms.PasswordInput)


class WithdrawForm(forms.Form):
    sum = forms.CharField()

webinterface/views.py
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView
from django.views.generic import View
from django.shortcuts import redirect
from django.contrib.auth.hashers import make_password
from webinterface.models import Card, Operations
from webinterface.forms import *
from django.conf import settings


class ExitView(View):
    def get(self, request, *args, **kwargs):
        self.request.session.flush()
        return redirect('webinterface:atm')


class AtmView(FormView):
    template_name = 'webinterface/atm.html'
    form_class = CardNumForm
    success_url = "/atm/pin"

    def form_valid(self, request, *args, **kwargs):
        nm = self.request.POST['number'].replace(" ", "")
        hashed = make_password(nm, salt=settings.SECRET_KEY)
        search_results = Card.objects.filter(hashed=hashed)
        if not search_results:
            return redirect('webinterface:error', error='NOT_FOUND')
        if search_results[0].pin_block:
            return redirect('webinterface:error', error='BLOCKED')
        self.request.session['key'] = search_results[0].id
        return super(AtmView, self).form_valid(request, *args, **kwargs)


class WithdrawView(FormView):
    template_name = 'webinterface/withdraw.html'
    form_class = WithdrawForm
    success_url = "/atm/result"

    def get(self, request, *args, **kwargs):
        if not self.request.session.get('auth', None):
            return redirect('webinterface:error', error='NOTAUTH')
        return super(WithdrawView, self).get(request, *args, **kwargs)

    def form_valid(self, request, *args, **kwargs):
        sum = int(self.request.POST['sum'])
        id = self.request.session['key']
        card = Card.objects.get(id=id)
        if card.balance < sum:
            return redirect('webinterface:error', error='EXCESS')
        else:
            card.balance -= sum
            Card.objects.filter(id=id).update(balance=card.balance)
            op = Operations(card=card.number, code='WITHDRAW', sum=sum)
            op.save()
            return redirect('webinterface:balance')


class PinView(FormView):
    template_name = 'webinterface/pin.html'
    form_class = CardPinForm
    success_url = "/atm/operations"

    def form_valid(self, request, *args, **kwargs):
        pin = self.request.POST['pin']
        hashed = make_password(pin, salt=settings.SECRET_KEY)
        id = self.request.session['key']
        card = Card.objects.get(id=id)
        if card.pin != hashed:
            print(card.pin_attempts)
            print(card.pin_block)
            attempts = card.pin_attempts
            if attempts < 4:
                attempts += 1
                Card.objects.filter(id=id).update(pin_attempts=attempts)
                return redirect('webinterface:error', error='BADPIN')
            else:
                Card.objects.filter(id=id).update(pin_block=True)
                return redirect('webinterface:error', error='BLOCKED')
        self.request.session['auth'] = True
        return super(PinView, self).form_valid(request, *args, **kwargs)


class ErrorView(TemplateView):
    template_name = 'webinterface/error.html'

    def get_context_data(self, **kwargs):
        context = super(ErrorView, self).get_context_data(**kwargs)
        return context

class OperationsView(TemplateView):
    template_name = 'webinterface/operations.html'

    def get(self, request, *args, **kwargs):
        if not self.request.session.get('auth', None):
            return redirect('webinterface:error', error='NOTAUTH')
        return super(OperationsView, self).get(request, *args, **kwargs)


class BalanceView(TemplateView):
    template_name = 'webinterface/balance.html'

    def get(self, request, *args, **kwargs):
        if not self.request.session.get('auth', None):
            return redirect('webinterface:error', error='NOTAUTH')
        id = self.request.session['key']
        card = Card.objects.get(id=id)
        op = Operations(card=card.number, code='OP_VIEW')
        op.save()
        return super(BalanceView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(BalanceView, self).get_context_data()
        id = self.request.session['key']
        card = Card.objects.get(id=id)
        context['number'] = card.number
        context['balance'] = card.balance
        return context

webinterface/templates/webinterface/atm.html
{% extends 'webinterface/base.html' %}
{% load static %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style>
    .demo-container {
        width: 100%;
        max-width: 350px;
        margin: 50px auto;
    }
    form {
        margin: 30px;
    }
</style>
<link href="{% static 'webinterface/css/keypad.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
    <h1 class="cover-heading">Please enter card number</h1>
    <div class="demo-container">
        <div class='card-wrapper'></div>
        <div class="form-container active">
            <form role="form" class="form-inline" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" id="number" name="number" maxlength="16" readonly>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">OK</button>
            </form>
        </div>
        {% include "webinterface/keypad.html" %}
    </div>
{% endblock %}
{% block javascript_bottom %}
    <!-- <script src="{% static 'webinterface/js/card.js' %}" type="text/javascript"></script>-->
    <script src="{% static 'webinterface/js/keypad.jquery.js' %}" type="text/javascript"></script>
{% endblock %}

webinterface/templates/webinterface/balance.html
{% extends 'webinterface/base.html' %}
{% load static %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style>
    .demo-container {
        width: 100%;
        max-width: 350px;
        margin: 50px auto;
    }
    form {
        margin: 30px;
    }
</style>
{% endblock %}
{% block content %}
    <h1 class="cover-heading danger">Your balance</h1>
    <p class="lead">Card <em>{{ number }}</em> has {{ balance }}</p>
    <p>{% now "jS F Y H:i" %}</p>
    <p class="lead">
        <a href="javascript:history.back()" class="btn btn-lg btn-default">Back</a>
        <a href="{% url 'webinterface:exit' %}" class="btn btn-lg btn-warning">Exit</a>
    </p>
{% endblock %}

webinterface/templates/webinterface/base.html
{% load static %}
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% trans "Cash Machine" %}</title>

    <!-- start: Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- end: Mobile Specific -->

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'webinterface/favicon.ico' %}"/>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'webinterface/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="{% static 'webinterface/css/style.css' %}" rel="stylesheet" type="text/css">

    {% block extrahead %}
    {% endblock %}

</head>
<body>
    <div class="site-wrapper">
        <div class="site-wrapper-inner">
            <div class="cover-container">
                <div class="masthead clearfix">
                    <div class="inner">
                        <h3 class="masthead-brand">{% trans "Cash Machine" %}</h3>
                    </div>
                </div>

                <div class="inner cover">
                    {% block content %}{% endblock %}
                </div>

                <div class="mastfoot">
                    <div class="inner">
                        <p>Powered by <a href="http://getbootstrap.com">Bootstrap</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- start: JavaScript-->
    <!-- jQuery -->
    <script src="{% static 'webinterface/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'webinterface/js/bootstrap.min.js' %}" type="text/javascript"></script>

    {% block javascript_bottom %}
    {% endblock %}
</body>
</html>

webinterface/templates/webinterface/error.html
{% extends 'webinterface/base.html' %}
{% load static %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style>
    .demo-container {
        width: 100%;
        max-width: 350px;
        margin: 50px auto;
    }
    form {
        margin: 30px;
    }
</style>
{% endblock %}
{% block content %}
    <h1 class="cover-heading danger">
    {% if error == "NOT_FOUND" %}CARD NOT FOUND
    {% elif error == "BLOCKED" %}CARD BLOCKED
    {% elif error == "BADPIN" %}INCORRECT PIN
    {% elif error = "NOTAUTH" %}NOT AUTHENTICATED
    {% elif error = "EXCESS" %}INSUFFICIENT FUNDS
    {% endif %}
    </h1>
    <p class="lead">
        <a href="javascript:history.back()" class="btn btn-lg btn-default">Back</a>
    </p>
{% endblock %}

webinterface/templates/webinterface/keypad.html
<div id="keypad">
    <div class="keys">
        <span id="7">7</span>
        <span id="8">8</span>
        <span id="9">9</span>
        <span id="4">4</span>
        <span id="5">5</span>
        <span id="6">6</span>
        <span id="1">1</span>
        <span id="2">2</span>
        <span id="3">3</span>
        <span id="0">0</span>
        <span id="C" class="clear">Clear</span>
    </div>
</div>

webinterface/templates/webinterface/operations.html
{% extends 'webinterface/base.html' %}
{% load static %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style>
    .demo-container {
        width: 100%;
        max-width: 350px;
        margin: 50px auto;
    }
    form {
        margin: 30px;
    }
</style>
{% endblock %}
{% block content %}
    <h1 class="cover-heading danger">Available operations</h1>
    <p class="lead">
        <a href="{% url 'webinterface:balance' %}" class="btn btn-lg btn-info">View balance</a>
        <a href="{% url 'webinterface:withdraw' %}" class="btn btn-lg btn-success">Withdraw money</a>
        <a href="{% url 'webinterface:exit' %}" class="btn btn-lg btn-warning">Exit</a>
    </p>
{% endblock %}

webinterface/templates/webinterface/pin.html
{% extends 'webinterface/base.html' %}
{% load static %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style>
    .demo-container {
        width: 100%;
        max-width: 400px;
        margin: 50px auto;
    }
    form {
        margin: 30px;
    }
</style>
<link href="{% static 'webinterface/css/keypad.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
    <h1 class="cover-heading">Please enter your pin</h1>
    <div class="demo-container">
        <div class="form-container active">
            <form role="form" class="form-inline" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group">
                        <input type="password" class="form-control" id="pin" name="pin" maxlength="4" readonly>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">OK</button>
                <a href="{% url 'webinterface:exit' %}" class="btn btn-warning">Exit</a>
            </form>
        </div>
        {% include "webinterface/keypad.html" %}
    </div>
{% endblock %}
{% block javascript_bottom %}
<script src="{% static 'webinterface/js/keypad.jquery.js' %}" type="text/javascript"></script>
{% endblock %}

webinterface/templates/webinterface/withdraw.html
{% extends 'webinterface/base.html' %}
{% load static %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style>
    .demo-container {
        width: 100%;
        max-width: 400px;
        margin: 50px auto;
    }
    form {
        margin: 30px;
    }
</style>
<link href="{% static 'webinterface/css/keypad.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
    <h1 class="cover-heading">Please enter sum</h1>
    <div class="demo-container">
        <div class='card-wrapper'></div>
        <div class="form-container active">
            <form role="form" class="form-inline" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" id="sum" name="sum" maxlength="16" readonly>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">OK</button>
                <a href="javascript:history.back()" class="btn btn-default">Back</a>
            </form>
        </div>
        {% include "webinterface/keypad.html" %}
    </div>
{% endblock %}
{% block javascript_bottom %}
    <!-- <script src="{% static 'webinterface/js/card.js' %}" type="text/javascript"></script>-->
    <script src="{% static 'webinterface/js/keypad.jquery.js' %}" type="text/javascript"></script>
{% endblock %}